---
# bootstrap_user: root
ntpserver: at.pool.ntp.org

ansible_ssh_private_key_file: ~/.ssh/ansible-control-host
all_source_directory: ~/RnD/Source/demo_assets
installfiles_location: "{{ all_source_directory }}/UCD"
download_dir: /tmp/downloads

add_user: ["sysadmin", "ibmuser", "lnxadm"]
sudo_user: ["sysadmin", "lnxadm"]
# password is Passw0rd

# Base install control
base_fqdn_set: true
base_firewall_rules: true

base_docker_install: true

base_java_install: true
base_java_vendor: openjdk
base_java_type: jdk
base_java_version: "11"
# get installationfiles from online locations or from local/host
base_download_online: false
