---
bootstrap_user: root
ntpserver: at.pool.ntp.org

ansible_ssh_private_key_file: ~/.ssh/ansible-control-host
all_source_directory: ~/Source/demo_assets
installfiles_location: "{{ all_source_directory }}/UCD" 
download_dir: /tmp/downloads

add_user: ["lnxadm", "ucd"]



# Base install control 
base_docker_install: yes 

base_java_install: yes
base_java_vendor: openjdk
base_java_type: jre
base_java_version: 8