---
collections:
  - name: robertdebock.roles
roles:
#   - name: robertdebock.bootstrap
  - name: geerlingguy.repo-epel
#   - name: robertdebock.update
#   - name: robertdebock.buildtools
#   - name: robertdebock.java
  - name: geerlingguy.mysql
  - name: geerlingguy.docker
  - name: holms.fqdn