---
- hosts: ucd_server
  become: yes
  tasks:
    - name: include variables from group_vars
      include_vars:
        dir: group_vars

    - name: include variables from vars
      include_vars:
        dir: vars

    - name: Firewalld settings
      firewalld:
        port: "{{ item.port }}/{{ item.protocol }}"
        permanent: yes
        immediate: yes
        state: enabled
      with_items:
      - { port: "{{ mysql_port }}", protocol: "tcp" }
      - { port: "{{ install_server_web_https_port }}", protocol: "tcp" }
      - { port: "{{ agentcomm_uri_port }}", protocol: "tcp" }
      when: ansible_facts['os_family'] == "RedHat"

    - name: UFW settings
      ufw:
        port: "{{ item.port }}"
        proto: "{{ item.protocol }}"
        rule: allow
        state: enabled
      with_items:
      - { port: "{{ mysql_port }}", protocol: "tcp" }
      - { port: "{{ install_server_web_https_port }}", protocol: "tcp" }
      - { port: "{{ agentcomm_uri_port }}", protocol: "tcp" }
      when: ansible_facts['os_family'] == "Ubuntu"
