---
- name: Setup firewall rules
  hosts: ucd_server
  become: true
  tasks:
    - name: Include variables from group_vars
      ansible.builtin.include_vars:
        dir: group_vars

    - name: Include variables from vars
      ansible.builtin.include_vars:
        dir: vars

    - name: Firewalld settings
      ansible.posix.firewalld:
        port: "{{ item.port }}/{{ item.protocol }}"
        permanent: true
        immediate: true
        state: enabled
      with_items:
      - { port: "{{ mysql_port }}", protocol: "tcp" }
      - { port: "{{ install_server_web_https_port }}", protocol: "tcp" }
      - { port: "{{ agentcomm_uri_port }}", protocol: "tcp" }
      when: ansible_facts['os_family'] == "RedHat"

    - name: UFW settings
      community.general.ufw:
        port: "{{ item.port }}"
        proto: "{{ item.protocol }}"
        rule: allow
        state: enabled
      with_items:
      - { port: "{{ mysql_port }}", protocol: "tcp" }
      - { port: "{{ install_server_web_https_port }}", protocol: "tcp" }
      - { port: "{{ agentcomm_uri_port }}", protocol: "tcp" }
      when: ansible_facts['os_family'] == "Ubuntu"
