---
- name: Install UCD Server
  hosts: ucd_server
  become: true
  tasks:

  - name: Include variables
    ansible.builtin.include_vars:
      file: group_vars/db_server.yml
      name: dbserver

  - name: Include specific ucd variables
    ansible.builtin.include_vars:
      dir: "group_vars"

  - name: Create a download directory if not exists
    ansible.builtin.file:
      path: "{{ download_dir }}"
      state: directory
      recurse: true

  - name: Download ucd installation pack offline
    ansible.builtin.copy:
      src: "{{ ucd_installfiles_location }}/{{ ucds_file_name }}.{{ ucds_file_extension }}"
      dest: "{{ download_dir }}"
      mode: '0644'
    when: not base_download_online

  - name: Download ucd installation pack online
    ansible.builtin.get_url:
      url: "{{ ucd_files_online_location }}/{{ ucds_file_name }}.{{ ucds_file_extension }}"
      dest: "{{ download_dir }}"
      mode: '0644'
    when: base_download_online

  - name: Unzip ucd installation pack
    ansible.builtin.unarchive:
      src: "{{ download_dir }}/{{ ucds_file_name }}.{{ ucds_file_extension }}"
      dest: "{{ download_dir }}"
      creates: "{{ download_dir }}/{{ ucds_install_dir_name }}"
      remote_src: true

  - name: Download jdbc-driver/connector for mariadb/mysql online
    ansible.builtin.get_url:
      url: "https://dev.mysql.com/get/Downloads/Connector-J/{{ mysql_connector_file_name }}.{{ mysql_connector_file_extension }}"
      dest: "{{ download_dir }}"
      mode: '0644'
    when: base_download_online

  - name: Download jdbc-driver/connector for mariadb/mysql offline
    ansible.builtin.copy:
      src: "{{ mysql_connector_directory }}/{{ mysql_connector_file_name }}.{{ mysql_connector_file_extension }}"
      dest: "{{ download_dir }}"
      mode: '0644'
    when: not base_download_online

  # all_source_directory
  - name: Unzip jdbc-driver/connector for mariadb/mysql
    ansible.builtin.unarchive:
      src: "{{ download_dir }}/{{ mysql_connector_file_name }}.{{ mysql_connector_file_extension }}"
      dest: "{{ download_dir }}"
      creates: "{{ download_dir }}/{{ mysql_connector_install_dir }}"
      remote_src: true

  - name: Copy jar file to ucd installation directory
    ansible.builtin.copy:
      src: "{{ download_dir }}/{{ mysql_connector_install_dir }}/{{ mysql_connector_file_name }}.jar"
      dest: "{{ download_dir }}/{{ ucds_install_dir_name }}/lib/ext/{{ mysql_connector_file_name }}.jar"
      remote_src: true
      force: false
      mode: '0644'

  - name: Update ucd installation properties
    ansible.builtin.template:
      src: templates/install.properties.j2
      dest: "{{ download_dir }}/{{ ucds_install_dir_name }}/install.properties"
      mode: '0644'
    vars:
      install_ucd_dir: "{{ install_server_dir }}"
      install_server_web_host: "{{ ucd_server_hostname }}"
      dbusername: "{{ dbserver.ucdserver_dbuser }}"
      dbpassword: "{{ dbserver.ucdserver_upassword }}"
      dbhostname: "{{ dbserver.mysql_hostname }}"
      dbname: "{{ dbserver.ucdserver_dbname }}"
      dbport: "{{ dbserver.mysql_port }}"

  - name: Install UCD silently
    ansible.builtin.command: "sh ./install-server.sh -silent -install-dir {{ install_server_dir }} -java-home {{ lookup('ansible.builtin.env', 'JAVA_HOME') }}"
    # shell: ./install-server.sh -silent -install-dir {{ install_server_dir }} -java-home /usr/lib/jvm/jre
    register: ucdsinstalllog
    args:
      chdir: "{{ download_dir }}/{{ ucds_install_dir_name }}"
      creates: "{{ download_dir }}/{{ ucds_install_dir_name }}/{{ ucds_install_log_name }}"

  - name: Create ucdsinstall.log
    ansible.builtin.copy:
      content: "{{  ucdsinstalllog }}"
      dest: "{{ download_dir }}/{{ ucds_install_dir_name }}/{{ ucds_install_log_name }}"
      mode: '0644'

  - name: Update ucd service properties
    ansible.builtin.template:
        src: "{{ ucds_service_file }}.j2"
        dest: "/etc/systemd/system/{{ ucds_service_file }}"
        mode: '0644'
    vars:
        installation_location: "{{ install_server_dir }}"
        service_user: "{{ ucd_server_user }}"
        service_group: "{{ ucd_server_group }}"

  - name: Grant read and execute permissions to service
    become: true
    ansible.builtin.file:
        path: "/etc/systemd/system/{{ ucds_service_file }}"
        mode: '0755'

  - name: Change ownership of UCDS installation direcotry
    become: true
    ansible.builtin.file:
        path: "{{ install_server_dir }}"
        owner: "{{ ucd_server_user }}"
        group: "{{ ucd_server_group }}"

# TODO: use ansible systemd module!
  - name: Start UCDS service
    become: true
    ansible.builtin.service:
      name: "{{ ucds_service_name }}"
      enabled: true
      state: started

# wait so that service is up and running!
  - name: Wait for starting the service
    ansible.builtin.pause:
      seconds: 20
